# Generated by Django 5.0.7 on 2024-07-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motos_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moto',
        ),
    ]
