# Generated by Django 5.0.7 on 2024-07-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motos_api', '0002_delete_moto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=30)),
                ('trademark', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=150)),
                ('supplier', models.CharField(max_length=60)),
            ],
        ),
    ]
